Feed2X:
  cron: "*/30 * * * * *" # Treatment launch CRON expression. By default, starts every 30 seconds
  nLastMessages: 10 # NB last messages to read, not meant to change after release

RSSFeedReader:
  urls: https://mastodon.social/@guillaume_faudemer.rss # RSS Feed URL to read messages from

logging:
  level:
    org:
      kakamu: DEBUG